name: '[FE] Push To Registry'
run-name: 'Build for ${{ inputs.environment }}, Auto=${{ inputs.auto_tag }}, Sub=${{ inputs.sub-env }}'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (prod, staging, dev)'
        required: true
        type: choice
        options:
          - prod
          - staging
          - dev
      sub-env:
        description: 'Sub Environment (like fe, be)'
        required: true
        default: none
        type: choice
        options:
          - none
          - fe
          - be
      auto_tag:
        description: 'Whether to autoincrement tag'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3      
        
      - name: Prepare Env, Tag and Push
        uses: ./.github/actions/prepare-and-push
        with:
          environment: ${{ inputs.environment }}
          sub-env: ${{ inputs.sub-env }}
          auto_tag: ${{ inputs.auto_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}} 
